// Generated by gencpp from file ars548_msg/DopplerPoint.msg
// DO NOT EDIT!


#ifndef ARS548_MSG_MESSAGE_DOPPLERPOINT_H
#define ARS548_MSG_MESSAGE_DOPPLERPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace ars548_msg
{
template <class ContainerAllocator>
struct DopplerPoint_
{
  typedef DopplerPoint_<ContainerAllocator> Type;

  DopplerPoint_()
    : position()
    , doppler_velocity(0.0)  {
    }
  DopplerPoint_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , doppler_velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _doppler_velocity_type;
  _doppler_velocity_type doppler_velocity;





  typedef boost::shared_ptr< ::ars548_msg::DopplerPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ars548_msg::DopplerPoint_<ContainerAllocator> const> ConstPtr;

}; // struct DopplerPoint_

typedef ::ars548_msg::DopplerPoint_<std::allocator<void> > DopplerPoint;

typedef boost::shared_ptr< ::ars548_msg::DopplerPoint > DopplerPointPtr;
typedef boost::shared_ptr< ::ars548_msg::DopplerPoint const> DopplerPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ars548_msg::DopplerPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ars548_msg::DopplerPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ars548_msg::DopplerPoint_<ContainerAllocator1> & lhs, const ::ars548_msg::DopplerPoint_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.doppler_velocity == rhs.doppler_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ars548_msg::DopplerPoint_<ContainerAllocator1> & lhs, const ::ars548_msg::DopplerPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ars548_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ars548_msg::DopplerPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_msg::DopplerPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_msg::DopplerPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f48bf426714c21dd97cb6b3037b7ee7";
  }

  static const char* value(const ::ars548_msg::DopplerPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f48bf426714c21dULL;
  static const uint64_t static_value2 = 0xd97cb6b3037b7ee7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ars548_msg/DopplerPoint";
  }

  static const char* value(const ::ars548_msg::DopplerPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32 position\n"
"float32 doppler_velocity\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::ars548_msg::DopplerPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.doppler_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DopplerPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ars548_msg::DopplerPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ars548_msg::DopplerPoint_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "doppler_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.doppler_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARS548_MSG_MESSAGE_DOPPLERPOINT_H
